const sharp = require('sharp');
const path = require('path');
const fs = require('fs').promises;
const crypto = require('crypto');

/**
 * Generate voucher image by overlaying code on template
 * @param {string} voucherCode - The voucher code to overlay
 * @param {string} voucherType - The voucher type
 * @returns {Promise<string>} - Path to generated image
 */
async function generateVoucherImage(voucherCode, voucherType) {
  try {
    // Ensure templates and uploads directories exist
    const templatesDir = path.join(__dirname, '../../templates');
    const uploadsDir = path.join(__dirname, '../../uploads');
    await fs.mkdir(templatesDir, { recursive: true });
    await fs.mkdir(uploadsDir, { recursive: true });
    
    // Determine template based on type
    const templateMap = {
      'Promo Edukasi': 'template-education.png',
      'Diskon Game': 'template-game.png',
    };
    
    const templateName = templateMap[voucherType] || 'template-default.png';
    const templatePath = path.join(templatesDir, templateName);
    
    // Check if template exists, if not create a default one
    try {
      await fs.access(templatePath);
    } catch (error) {
      // Create a default template if it doesn't exist
      await createDefaultTemplate(templatePath, voucherType);
    }
    
    // Create SVG text overlay
    const svgText = `
      <svg width="800" height="400">
        <style>
          .code { 
            fill: #ffffff; 
            font-size: 48px; 
            font-weight: bold; 
            font-family: Arial, sans-serif;
          }
        </style>
        <text x="400" y="250" text-anchor="middle" class="code">${voucherCode}</text>
      </svg>
    `;
    
    const svgBuffer = Buffer.from(svgText);
    
    // Output path with UUID to prevent conflicts
    const randomId = crypto.randomUUID();
    const outputFilename = `voucher-${randomId}-${voucherCode.replace(/\//g, '-')}.png`;
    const outputPath = path.join(uploadsDir, outputFilename);
    
    // Composite the text onto the template
    await sharp(templatePath)
      .composite([
        {
          input: svgBuffer,
          top: 0,
          left: 0,
        }
      ])
      .toFile(outputPath);
    
    return outputFilename;
  } catch (error) {
    console.error('Error generating voucher image:', error);
    throw error;
  }
}

/**
 * Create a default template image
 */
async function createDefaultTemplate(templatePath, voucherType) {
  const color = voucherType === 'Promo Edukasi' ? '#3b82f6' : '#8b5cf6';
  
  const svg = `
    <svg width="800" height="400">
      <rect width="800" height="400" fill="${color}"/>
      <text x="400" y="100" text-anchor="middle" fill="white" font-size="36" font-family="Arial" font-weight="bold">
        ${voucherType}
      </text>
      <text x="400" y="350" text-anchor="middle" fill="white" font-size="16" font-family="Arial">
        Generated by VouchGen
      </text>
    </svg>
  `;
  
  // Ensure directory exists
  await fs.mkdir(path.dirname(templatePath), { recursive: true });
  
  await sharp(Buffer.from(svg))
    .png()
    .toFile(templatePath);
}

module.exports = { generateVoucherImage };
